servo_node:
  ros__parameters:
    dry_run: true
    required: true
    port: "/dev/stm32_servo"
    manufacturer: "STMicroelectronics"
    baudrate: 115200
    command_min: 0
    command_max: 255
    initial_command: 0
    drop_command: 1
    write_period: 0.1
    continuous_write: false
    status_period: 1.0
    legacy_parameter_name: "/servo/servo"
